# 1.1 Стохастический градиентный спуск

Вариант 3: SGD с Mini-batch
Реализуйте SGD с мини-батчами размером 10. 

Сгенерируйте 100 точек данных: 
$$
y = 3 \cdot x + 1 + \varepsilon.
$$

Начальные веса: w=10, b=10. Скорость обучения 0.02. 

Сравните траекторию с обычным SGD.

Требуется:

1. Сгенерировать данные согласно описанию
2. Реализовать указанную модификацию SGD
3. Обучить модель, вывести финальные параметры
4. Построить график сходимости


```py
import numpy as np
import matplotlib.pyplot as plt

# Ваш код здесь
# ...

print(f"Финальные параметры: w = {w:.4f}, b = {b:.4f}")
print(f"Финальный loss: {loss:.6f}")
```

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)

# 1) Данные: y = 3x + 1 + eps
n = 100
x = np.random.uniform(-5, 5, n)
eps = np.random.normal(0, 1, n)
y = 3 * x + 1 + eps

lr = 0.02
epochs = 50

def mse(w, b):
    return np.mean((w * x + b - y) ** 2)

def train(batch_size):
    w, b = 10.0, 10.0
    losses = []

    for _ in range(epochs):
        idx = np.random.permutation(n)
        for i in range(0, n, batch_size):
            batch = idx[i:i + batch_size]
            xb, yb = x[batch], y[batch]

            # предсказание и ошибка
            err = (w * xb + b) - yb

            # градиенты MSE
            dw = 2 * np.mean(err * xb)
            db = 2 * np.mean(err)

            # шаг градиентного спуска
            w -= lr * dw
            b -= lr * db

            # для сравнения считаем loss на ВСЕХ данных
            losses.append(mse(w, b))

    return w, b, losses

# 2) Обучение
w_sgd, b_sgd, loss_sgd = train(batch_size=1)
w_mb,  b_mb,  loss_mb  = train(batch_size=10)

# 3) Вывод
print(f"SGD (batch=1):  w = {w_sgd:.4f}, b = {b_sgd:.4f}, loss = {loss_sgd[-1]:.6f}")
print(f"Mini-batch=10: w = {w_mb:.4f},  b = {b_mb:.4f},  loss = {loss_mb[-1]:.6f}")

# 4) График сходимости
plt.plot(loss_sgd, label="SGD (batch=1)")
plt.plot(loss_mb,  label="Mini-batch (10)")
plt.xlabel("Шаг обновления")
plt.ylabel("MSE loss (на всех данных)")
plt.legend()
plt.grid(True)
plt.show()

# 1.2 Однослойный и многослойный персептрон

Вариант 5. Персептрон для классификации ирисов (2 класса)

Загрузите датасет ирисов (sklearn.datasets.load_iris()). Возьмите только два класса (setosa и versicolor) и два признака (длина и ширина чашелистика). Обучите персептрон. Выведите веса и точность.

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

iris = load_iris()
X = iris.data[:, :2]          # длина и ширина чашелистика
y = iris.target

# берем только setosa и versicolor
mask = y < 2
X, y = X[mask], y[mask]

model = Perceptron(max_iter=1000, eta0=0.1, random_state=0)
model.fit(X, y)

y_pred = model.predict(X)

print("Веса:", model.coef_)
print("Смещение:", model.intercept_)
print("Точность:", accuracy_score(y, y_pred))

X shape: (150, 4)
y shape: (150,)
Веса: [[ 2.32 -3.87]]
Смещение: [-0.5]
Точность: 0.99


# 1.3 Рекомендательные системы

Вариант 1. Базовая user-item матрица
Реализуйте функцию create_user_item_matrix(n_users, n_items, interactions), которая создает матрицу взаимодействий пользователь-товар. На вход подается список взаимодействий в формате [(user_id, item_id, rating), ...]. Матрица должна иметь размер n_users x n_items, где на пересечении user_id и item_id стоит рейтинг, иначе 0. Выведите полученную матрицу для 5 пользователей и 5 товаров со случайными взаимодействиями.

In [4]:
import numpy as np
import random

def create_user_item_matrix(n_users, n_items, interactions):
    matrix = np.zeros((n_users, n_items))
    for user_id, item_id, rating in interactions:
        matrix[user_id][item_id] = rating
    return matrix



n_users, n_items = 5, 5
interactions = []
for _ in range(8): 
    u = random.randint(0, n_users - 1)
    i = random.randint(0, n_items - 1)
    r = random.randint(1, 5)
    interactions.append((u, i, r))

print("Взаимодействия:", interactions)

matrix = create_user_item_matrix(n_users, n_items, interactions)

print("\nUser-Item матрица:")
print(matrix)

Взаимодействия: [(4, 0, 5), (2, 0, 1), (1, 2, 5), (2, 2, 4), (0, 2, 3), (3, 0, 4), (3, 0, 2), (1, 3, 3)]

User-Item матрица:
[[0. 0. 3. 0. 0.]
 [0. 0. 5. 3. 0.]
 [1. 0. 4. 0. 0.]
 [2. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]]


# 1.5 Трансформеры. NLP

Вариант 4. Фильм: "Темный рыцарь" (The Dark Knight)
Используя предобученную модель для поиска ответов на вопросы (question-answering), извлеките информацию из краткого описания фильма. Для каждого вопроса программа должна найти фрагмент текста, содержащий ответ.

Модель: electra-base-squad2.

Вопросы: Кто злодей в фильме? Кто играет Бэтмена?

In [ ]:
from transformers import pipeline

context = """
The Dark Knight is a 2008 superhero film directed by Christopher Nolan.
Batman is played by Christian Bale. In Gotham City, Batman faces a criminal mastermind known as the Joker,
who plunges the city into chaos.
""".strip()

qa = pipeline("question-answering", model="deepset/electra-base-squad2")

questions = [
    "Who is the villain in the film?",
    "Who plays Batman?"
]

for q in questions:
    res = qa(question=q, context=context)
    print(f"Q: {q}")
    print(f"A: {res['answer']} (score={res['score']:.3f})\n")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 209.27it/s, Materializing param=qa_outputs.weight]                                         


Q: Who is the villain in the film?
A: the Joker (score=0.956)

Q: Who plays Batman?
A: Christian Bale (score=1.000)

